### PR TITLE
Change code to make everything work in C# instead of Python.

### PR DESCRIPTION
**Pull request by Tiebe**
As the title states, this converts everything to work in C#. If I need to change anything just tell me!

### CODE REVIEW

**Comment by Tiebe** [comment]
This should also almost be cross-platform. I believe only some more changes to WebdriverManager.cs and that should do it.

**Comment by Tiebe** [comment]
That should work.

**Comment by DhrumanGupta** [comment]
Hey, I tried out the code, and it gave me the following error.

```
Exception thrown: 'Newtonsoft.Json.JsonReaderException' in Newtonsoft.Json.dll
Exception thrown: 'Newtonsoft.Json.JsonReaderException' in Newtonsoft.Json.dll
Exception thrown: 'Newtonsoft.Json.JsonReaderException' in Newtonsoft.Json.dll
Exception thrown: 'Newtonsoft.Json.JsonReaderException' in System.Private.CoreLib.dll
Exception thrown: 'Newtonsoft.Json.JsonReaderException' in System.Private.CoreLib.dll
Exception thrown: 'Newtonsoft.Json.JsonReaderException' in System.Private.CoreLib.dll
An unhandled exception of type 'Newtonsoft.Json.JsonReaderException' occurred in System.Private.CoreLib.dll
Unexpected character encountered while parsing value: [. Path 'profileChanges', line 1, position 101.
```
It tried moving the type to dynamic (bad practice, but this was just to test) and also object (then parse to dynamic), and none of them worked either.

I found it to be these lines that cause this issue:
```cs
var response = JsonConvert.DeserializeObject<Dictionary<string, string>>(s);
var notifications = JsonConvert.DeserializeObject<Dictionary<string, string>>(response["notifications"]);
```
(Line 133 and 134 in Program.cs)

**Comment by Tiebe** [comment]
Hmm, strange. For me it builds normally, and runs normally. Maybe this is because you've already claimed the reward? Or is this error while building?

**Comment by Tiebe** [comment]
Oh wait I see the problem, the claiming should still work, it's just the output that fails parsing

**Comment by DhrumanGupta** [comment]
Yeah, that does sound like the issue.
I'll try this tomorrow when it works, and if it does claim, ill merge the pull request and make a few changes here and there

**Comment by Tiebe** [comment]
Should all work now!

**Pull request merged**
